# Generated by Django 6.0.3 on 2026-03-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
